// This file was autogenerated by PeakRDL-uvm
package csrng_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    import dv_base_reg_pkg::*;
    `include "csrng_covergroups.svh"
    // reg - csrng::INTERRUPT_STATE
    class csrng__INTERRUPT_STATE extends dv_base_reg;
        `uvm_object_utils(csrng__INTERRUPT_STATE)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INTERRUPT_STATE_bit_cg CS_CMD_REQ_DONE_bit_cg[1];
        csrng__INTERRUPT_STATE_bit_cg CS_ENTROPY_REQ_bit_cg[1];
        csrng__INTERRUPT_STATE_bit_cg CS_HW_INST_EXC_bit_cg[1];
        csrng__INTERRUPT_STATE_bit_cg CS_FATAL_ERR_bit_cg[1];
        csrng__INTERRUPT_STATE_fld_cg fld_cg;
        rand dv_base_reg_field CS_CMD_REQ_DONE;
        rand dv_base_reg_field CS_ENTROPY_REQ;
        rand dv_base_reg_field CS_HW_INST_EXC;
        rand dv_base_reg_field CS_FATAL_ERR;

        function new(string name = "csrng__INTERRUPT_STATE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CS_CMD_REQ_DONE = dv_base_reg_field::type_id::create("CS_CMD_REQ_DONE");
            this.CS_CMD_REQ_DONE.configure(this, 1, 0, "W1C", 1, 'h0, 0, 1, 1);
            this.CS_ENTROPY_REQ = dv_base_reg_field::type_id::create("CS_ENTROPY_REQ");
            this.CS_ENTROPY_REQ.configure(this, 1, 1, "W1C", 1, 'h0, 0, 1, 1);
            this.CS_HW_INST_EXC = dv_base_reg_field::type_id::create("CS_HW_INST_EXC");
            this.CS_HW_INST_EXC.configure(this, 1, 2, "W1C", 1, 'h0, 0, 1, 1);
            this.CS_FATAL_ERR = dv_base_reg_field::type_id::create("CS_FATAL_ERR");
            this.CS_FATAL_ERR.configure(this, 1, 3, "W1C", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CS_CMD_REQ_DONE_bit_cg[bt]) CS_CMD_REQ_DONE_bit_cg[bt] = new();
                foreach(CS_ENTROPY_REQ_bit_cg[bt]) CS_ENTROPY_REQ_bit_cg[bt] = new();
                foreach(CS_HW_INST_EXC_bit_cg[bt]) CS_HW_INST_EXC_bit_cg[bt] = new();
                foreach(CS_FATAL_ERR_bit_cg[bt]) CS_FATAL_ERR_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INTERRUPT_STATE

    // reg - csrng::INTERRUPT_ENABLE
    class csrng__INTERRUPT_ENABLE extends dv_base_reg;
        `uvm_object_utils(csrng__INTERRUPT_ENABLE)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INTERRUPT_ENABLE_bit_cg CS_CMD_REQ_DONE_bit_cg[1];
        csrng__INTERRUPT_ENABLE_bit_cg CS_ENTROPY_REQ_bit_cg[1];
        csrng__INTERRUPT_ENABLE_bit_cg CS_HW_INST_EXC_bit_cg[1];
        csrng__INTERRUPT_ENABLE_bit_cg CS_FATAL_ERR_bit_cg[1];
        csrng__INTERRUPT_ENABLE_fld_cg fld_cg;
        rand dv_base_reg_field CS_CMD_REQ_DONE;
        rand dv_base_reg_field CS_ENTROPY_REQ;
        rand dv_base_reg_field CS_HW_INST_EXC;
        rand dv_base_reg_field CS_FATAL_ERR;

        function new(string name = "csrng__INTERRUPT_ENABLE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CS_CMD_REQ_DONE = dv_base_reg_field::type_id::create("CS_CMD_REQ_DONE");
            this.CS_CMD_REQ_DONE.configure(this, 1, 0, "RW", 1, 'h0, 0, 1, 1);
            this.CS_ENTROPY_REQ = dv_base_reg_field::type_id::create("CS_ENTROPY_REQ");
            this.CS_ENTROPY_REQ.configure(this, 1, 1, "RW", 1, 'h0, 0, 1, 1);
            this.CS_HW_INST_EXC = dv_base_reg_field::type_id::create("CS_HW_INST_EXC");
            this.CS_HW_INST_EXC.configure(this, 1, 2, "RW", 1, 'h0, 0, 1, 1);
            this.CS_FATAL_ERR = dv_base_reg_field::type_id::create("CS_FATAL_ERR");
            this.CS_FATAL_ERR.configure(this, 1, 3, "RW", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CS_CMD_REQ_DONE_bit_cg[bt]) CS_CMD_REQ_DONE_bit_cg[bt] = new();
                foreach(CS_ENTROPY_REQ_bit_cg[bt]) CS_ENTROPY_REQ_bit_cg[bt] = new();
                foreach(CS_HW_INST_EXC_bit_cg[bt]) CS_HW_INST_EXC_bit_cg[bt] = new();
                foreach(CS_FATAL_ERR_bit_cg[bt]) CS_FATAL_ERR_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INTERRUPT_ENABLE

    // reg - csrng::INTERRUPT_TEST
    class csrng__INTERRUPT_TEST extends dv_base_reg;
        `uvm_object_utils(csrng__INTERRUPT_TEST)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INTERRUPT_TEST_bit_cg CS_CMD_REQ_DONE_bit_cg[1];
        csrng__INTERRUPT_TEST_bit_cg CS_ENTROPY_REQ_bit_cg[1];
        csrng__INTERRUPT_TEST_bit_cg CS_HW_INST_EXC_bit_cg[1];
        csrng__INTERRUPT_TEST_bit_cg CS_FATAL_ERR_bit_cg[1];
        csrng__INTERRUPT_TEST_fld_cg fld_cg;
        rand dv_base_reg_field CS_CMD_REQ_DONE;
        rand dv_base_reg_field CS_ENTROPY_REQ;
        rand dv_base_reg_field CS_HW_INST_EXC;
        rand dv_base_reg_field CS_FATAL_ERR;

        function new(string name = "csrng__INTERRUPT_TEST");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CS_CMD_REQ_DONE = dv_base_reg_field::type_id::create("CS_CMD_REQ_DONE");
            this.CS_CMD_REQ_DONE.configure(this, 1, 0, "WO", 1, 'h0, 0, 1, 1);
            this.CS_ENTROPY_REQ = dv_base_reg_field::type_id::create("CS_ENTROPY_REQ");
            this.CS_ENTROPY_REQ.configure(this, 1, 1, "WO", 1, 'h0, 0, 1, 1);
            this.CS_HW_INST_EXC = dv_base_reg_field::type_id::create("CS_HW_INST_EXC");
            this.CS_HW_INST_EXC.configure(this, 1, 2, "WO", 1, 'h0, 0, 1, 1);
            this.CS_FATAL_ERR = dv_base_reg_field::type_id::create("CS_FATAL_ERR");
            this.CS_FATAL_ERR.configure(this, 1, 3, "WO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CS_CMD_REQ_DONE_bit_cg[bt]) CS_CMD_REQ_DONE_bit_cg[bt] = new();
                foreach(CS_ENTROPY_REQ_bit_cg[bt]) CS_ENTROPY_REQ_bit_cg[bt] = new();
                foreach(CS_HW_INST_EXC_bit_cg[bt]) CS_HW_INST_EXC_bit_cg[bt] = new();
                foreach(CS_FATAL_ERR_bit_cg[bt]) CS_FATAL_ERR_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INTERRUPT_TEST

    // reg - csrng::ALERT_TEST
    class csrng__ALERT_TEST extends dv_base_reg;
        `uvm_object_utils(csrng__ALERT_TEST)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__ALERT_TEST_bit_cg RECOV_ALERT_bit_cg[1];
        csrng__ALERT_TEST_bit_cg FATAL_ALERT_bit_cg[1];
        csrng__ALERT_TEST_fld_cg fld_cg;
        rand dv_base_reg_field RECOV_ALERT;
        rand dv_base_reg_field FATAL_ALERT;

        function new(string name = "csrng__ALERT_TEST");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.RECOV_ALERT = dv_base_reg_field::type_id::create("RECOV_ALERT");
            this.RECOV_ALERT.configure(this, 1, 0, "WO", 1, 'h0, 0, 1, 1);
            this.FATAL_ALERT = dv_base_reg_field::type_id::create("FATAL_ALERT");
            this.FATAL_ALERT.configure(this, 1, 1, "WO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(RECOV_ALERT_bit_cg[bt]) RECOV_ALERT_bit_cg[bt] = new();
                foreach(FATAL_ALERT_bit_cg[bt]) FATAL_ALERT_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__ALERT_TEST

    // reg - csrng::REGWEN
    class csrng__REGWEN extends dv_base_reg;
        `uvm_object_utils(csrng__REGWEN)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__REGWEN_bit_cg REGWEN_bit_cg[1];
        csrng__REGWEN_fld_cg fld_cg;
        rand dv_base_reg_field REGWEN;

        function new(string name = "csrng__REGWEN");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.REGWEN = dv_base_reg_field::type_id::create("REGWEN");
            this.REGWEN.configure(this, 1, 0, "W0C", 1, 'h1, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(REGWEN_bit_cg[bt]) REGWEN_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__REGWEN

    // reg - csrng::CTRL
    class csrng__CTRL extends dv_base_reg;
        `uvm_object_utils(csrng__CTRL)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__CTRL_bit_cg ENABLE_bit_cg[4];
        csrng__CTRL_bit_cg SW_APP_ENABLE_bit_cg[4];
        csrng__CTRL_bit_cg READ_INT_STATE_bit_cg[4];
        csrng__CTRL_bit_cg FIPS_FORCE_ENABLE_bit_cg[4];
        csrng__CTRL_fld_cg fld_cg;
        rand dv_base_reg_field ENABLE;
        rand dv_base_reg_field SW_APP_ENABLE;
        rand dv_base_reg_field READ_INT_STATE;
        rand dv_base_reg_field FIPS_FORCE_ENABLE;

        function new(string name = "csrng__CTRL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.ENABLE = dv_base_reg_field::type_id::create("ENABLE");
            this.ENABLE.configure(this, 4, 0, "RW", 1, 'h9, 1, 1, 1);
            this.SW_APP_ENABLE = dv_base_reg_field::type_id::create("SW_APP_ENABLE");
            this.SW_APP_ENABLE.configure(this, 4, 4, "RW", 1, 'h9, 1, 1, 1);
            this.READ_INT_STATE = dv_base_reg_field::type_id::create("READ_INT_STATE");
            this.READ_INT_STATE.configure(this, 4, 8, "RW", 1, 'h9, 1, 1, 1);
            this.FIPS_FORCE_ENABLE = dv_base_reg_field::type_id::create("FIPS_FORCE_ENABLE");
            this.FIPS_FORCE_ENABLE.configure(this, 4, 12, "RW", 1, 'h9, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(ENABLE_bit_cg[bt]) ENABLE_bit_cg[bt] = new();
                foreach(SW_APP_ENABLE_bit_cg[bt]) SW_APP_ENABLE_bit_cg[bt] = new();
                foreach(READ_INT_STATE_bit_cg[bt]) READ_INT_STATE_bit_cg[bt] = new();
                foreach(FIPS_FORCE_ENABLE_bit_cg[bt]) FIPS_FORCE_ENABLE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__CTRL

    // reg - csrng::CMD_REQ
    class csrng__CMD_REQ extends dv_base_reg;
        `uvm_object_utils(csrng__CMD_REQ)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__CMD_REQ_bit_cg acmd_bit_cg[4];
        csrng__CMD_REQ_bit_cg clen_bit_cg[4];
        csrng__CMD_REQ_bit_cg flag0_bit_cg[4];
        csrng__CMD_REQ_bit_cg glen_bit_cg[13];
        csrng__CMD_REQ_fld_cg fld_cg;
        rand dv_base_reg_field acmd;
        rand dv_base_reg_field clen;
        rand dv_base_reg_field flag0;
        rand dv_base_reg_field glen;

        function new(string name = "csrng__CMD_REQ");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.acmd = dv_base_reg_field::type_id::create("acmd");
            this.acmd.configure(this, 4, 0, "WO", 1, 'h0, 0, 1, 1);
            this.clen = dv_base_reg_field::type_id::create("clen");
            this.clen.configure(this, 4, 4, "WO", 1, 'h0, 0, 1, 1);
            this.flag0 = dv_base_reg_field::type_id::create("flag0");
            this.flag0.configure(this, 4, 8, "WO", 1, 'h0, 0, 1, 1);
            this.glen = dv_base_reg_field::type_id::create("glen");
            this.glen.configure(this, 13, 12, "WO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(acmd_bit_cg[bt]) acmd_bit_cg[bt] = new();
                foreach(clen_bit_cg[bt]) clen_bit_cg[bt] = new();
                foreach(flag0_bit_cg[bt]) flag0_bit_cg[bt] = new();
                foreach(glen_bit_cg[bt]) glen_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__CMD_REQ

    // reg - csrng::RESEED_INTERVAL
    class csrng__RESEED_INTERVAL extends dv_base_reg;
        `uvm_object_utils(csrng__RESEED_INTERVAL)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__RESEED_INTERVAL_bit_cg RESEED_INTERVAL_bit_cg[32];
        csrng__RESEED_INTERVAL_fld_cg fld_cg;
        rand dv_base_reg_field RESEED_INTERVAL;

        function new(string name = "csrng__RESEED_INTERVAL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.RESEED_INTERVAL = dv_base_reg_field::type_id::create("RESEED_INTERVAL");
            this.RESEED_INTERVAL.configure(this, 32, 0, "RW", 1, 'hffffffff, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(RESEED_INTERVAL_bit_cg[bt]) RESEED_INTERVAL_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__RESEED_INTERVAL

    // reg - csrng::RESEED_COUNTER
    class csrng__RESEED_COUNTER extends dv_base_reg;
        `uvm_object_utils(csrng__RESEED_COUNTER)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__RESEED_COUNTER_bit_cg RESEED_COUNTER_bit_cg[32];
        csrng__RESEED_COUNTER_fld_cg fld_cg;
        rand dv_base_reg_field RESEED_COUNTER;

        function new(string name = "csrng__RESEED_COUNTER");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.RESEED_COUNTER = dv_base_reg_field::type_id::create("RESEED_COUNTER");
            this.RESEED_COUNTER.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(RESEED_COUNTER_bit_cg[bt]) RESEED_COUNTER_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__RESEED_COUNTER

    // reg - csrng::SW_CMD_STS
    class csrng__SW_CMD_STS extends dv_base_reg;
        `uvm_object_utils(csrng__SW_CMD_STS)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__SW_CMD_STS_bit_cg CMD_RDY_bit_cg[1];
        csrng__SW_CMD_STS_bit_cg CMD_ACK_bit_cg[1];
        csrng__SW_CMD_STS_bit_cg CMD_STS_bit_cg[3];
        csrng__SW_CMD_STS_fld_cg fld_cg;
        rand dv_base_reg_field CMD_RDY;
        rand dv_base_reg_field CMD_ACK;
        rand dv_base_reg_field CMD_STS;

        function new(string name = "csrng__SW_CMD_STS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CMD_RDY = dv_base_reg_field::type_id::create("CMD_RDY");
            this.CMD_RDY.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 1);
            this.CMD_ACK = dv_base_reg_field::type_id::create("CMD_ACK");
            this.CMD_ACK.configure(this, 1, 2, "RO", 1, 'h0, 1, 1, 1);
            this.CMD_STS = dv_base_reg_field::type_id::create("CMD_STS");
            this.CMD_STS.configure(this, 3, 3, "RO", 1, 'h0, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CMD_RDY_bit_cg[bt]) CMD_RDY_bit_cg[bt] = new();
                foreach(CMD_ACK_bit_cg[bt]) CMD_ACK_bit_cg[bt] = new();
                foreach(CMD_STS_bit_cg[bt]) CMD_STS_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__SW_CMD_STS

    // reg - csrng::GENBITS_VLD
    class csrng__GENBITS_VLD extends dv_base_reg;
        `uvm_object_utils(csrng__GENBITS_VLD)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__GENBITS_VLD_bit_cg GENBITS_VLD_bit_cg[1];
        csrng__GENBITS_VLD_bit_cg GENBITS_FIPS_bit_cg[1];
        csrng__GENBITS_VLD_fld_cg fld_cg;
        rand dv_base_reg_field GENBITS_VLD;
        rand dv_base_reg_field GENBITS_FIPS;

        function new(string name = "csrng__GENBITS_VLD");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.GENBITS_VLD = dv_base_reg_field::type_id::create("GENBITS_VLD");
            this.GENBITS_VLD.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 1);
            this.GENBITS_FIPS = dv_base_reg_field::type_id::create("GENBITS_FIPS");
            this.GENBITS_FIPS.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(GENBITS_VLD_bit_cg[bt]) GENBITS_VLD_bit_cg[bt] = new();
                foreach(GENBITS_FIPS_bit_cg[bt]) GENBITS_FIPS_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__GENBITS_VLD

    // reg - csrng::GENBITS
    class csrng__GENBITS extends dv_base_reg;
        `uvm_object_utils(csrng__GENBITS)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__GENBITS_bit_cg GENBITS_bit_cg[32];
        csrng__GENBITS_fld_cg fld_cg;
        rand dv_base_reg_field GENBITS;

        function new(string name = "csrng__GENBITS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.GENBITS = dv_base_reg_field::type_id::create("GENBITS");
            this.GENBITS.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(GENBITS_bit_cg[bt]) GENBITS_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__GENBITS

    // reg - csrng::INT_STATE_READ_ENABLE
    class csrng__INT_STATE_READ_ENABLE extends dv_base_reg;
        `uvm_object_utils(csrng__INT_STATE_READ_ENABLE)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INT_STATE_READ_ENABLE_bit_cg INT_STATE_READ_ENABLE_bit_cg[3];
        csrng__INT_STATE_READ_ENABLE_fld_cg fld_cg;
        rand dv_base_reg_field INT_STATE_READ_ENABLE;

        function new(string name = "csrng__INT_STATE_READ_ENABLE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.INT_STATE_READ_ENABLE = dv_base_reg_field::type_id::create("INT_STATE_READ_ENABLE");
            this.INT_STATE_READ_ENABLE.configure(this, 3, 0, "RW", 1, 'h7, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(INT_STATE_READ_ENABLE_bit_cg[bt]) INT_STATE_READ_ENABLE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INT_STATE_READ_ENABLE

    // reg - csrng::INT_STATE_READ_ENABLE_REGWEN
    class csrng__INT_STATE_READ_ENABLE_REGWEN extends dv_base_reg;
        `uvm_object_utils(csrng__INT_STATE_READ_ENABLE_REGWEN)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INT_STATE_READ_ENABLE_REGWEN_bit_cg INT_STATE_READ_ENABLE_REGWEN_bit_cg[1];
        csrng__INT_STATE_READ_ENABLE_REGWEN_fld_cg fld_cg;
        rand dv_base_reg_field INT_STATE_READ_ENABLE_REGWEN;

        function new(string name = "csrng__INT_STATE_READ_ENABLE_REGWEN");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.INT_STATE_READ_ENABLE_REGWEN = dv_base_reg_field::type_id::create("INT_STATE_READ_ENABLE_REGWEN");
            this.INT_STATE_READ_ENABLE_REGWEN.configure(this, 1, 0, "W0C", 1, 'h1, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(INT_STATE_READ_ENABLE_REGWEN_bit_cg[bt]) INT_STATE_READ_ENABLE_REGWEN_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INT_STATE_READ_ENABLE_REGWEN

    // reg - csrng::INT_STATE_NUM
    class csrng__INT_STATE_NUM extends dv_base_reg;
        `uvm_object_utils(csrng__INT_STATE_NUM)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INT_STATE_NUM_bit_cg INT_STATE_NUM_bit_cg[4];
        csrng__INT_STATE_NUM_fld_cg fld_cg;
        rand dv_base_reg_field INT_STATE_NUM;

        function new(string name = "csrng__INT_STATE_NUM");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.INT_STATE_NUM = dv_base_reg_field::type_id::create("INT_STATE_NUM");
            this.INT_STATE_NUM.configure(this, 4, 0, "RW", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(INT_STATE_NUM_bit_cg[bt]) INT_STATE_NUM_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INT_STATE_NUM

    // reg - csrng::INT_STATE_VAL
    class csrng__INT_STATE_VAL extends dv_base_reg;
        `uvm_object_utils(csrng__INT_STATE_VAL)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__INT_STATE_VAL_bit_cg INT_STATE_VAL_bit_cg[32];
        csrng__INT_STATE_VAL_fld_cg fld_cg;
        rand dv_base_reg_field INT_STATE_VAL;

        function new(string name = "csrng__INT_STATE_VAL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.INT_STATE_VAL = dv_base_reg_field::type_id::create("INT_STATE_VAL");
            this.INT_STATE_VAL.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(INT_STATE_VAL_bit_cg[bt]) INT_STATE_VAL_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__INT_STATE_VAL

    // reg - csrng::FIPS_FORCE
    class csrng__FIPS_FORCE extends dv_base_reg;
        `uvm_object_utils(csrng__FIPS_FORCE)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__FIPS_FORCE_bit_cg FIPS_FORCE_bit_cg[3];
        csrng__FIPS_FORCE_fld_cg fld_cg;
        rand dv_base_reg_field FIPS_FORCE;

        function new(string name = "csrng__FIPS_FORCE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.FIPS_FORCE = dv_base_reg_field::type_id::create("FIPS_FORCE");
            this.FIPS_FORCE.configure(this, 3, 0, "RW", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(FIPS_FORCE_bit_cg[bt]) FIPS_FORCE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__FIPS_FORCE

    // reg - csrng::HW_EXC_STS
    class csrng__HW_EXC_STS extends dv_base_reg;
        `uvm_object_utils(csrng__HW_EXC_STS)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__HW_EXC_STS_bit_cg HW_EXC_STS_bit_cg[16];
        csrng__HW_EXC_STS_fld_cg fld_cg;
        rand dv_base_reg_field HW_EXC_STS;

        function new(string name = "csrng__HW_EXC_STS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.HW_EXC_STS = dv_base_reg_field::type_id::create("HW_EXC_STS");
            this.HW_EXC_STS.configure(this, 16, 0, "W0C", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(HW_EXC_STS_bit_cg[bt]) HW_EXC_STS_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__HW_EXC_STS

    // reg - csrng::RECOV_ALERT_STS
    class csrng__RECOV_ALERT_STS extends dv_base_reg;
        `uvm_object_utils(csrng__RECOV_ALERT_STS)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__RECOV_ALERT_STS_bit_cg ENABLE_FIELD_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg SW_APP_ENABLE_FIELD_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg READ_INT_STATE_FIELD_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg FIPS_FORCE_ENABLE_FIELD_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg ACMD_FLAG0_FIELD_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg CS_BUS_CMP_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg CMD_STAGE_INVALID_ACMD_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg CMD_STAGE_INVALID_CMD_SEQ_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_bit_cg CMD_STAGE_RESEED_CNT_ALERT_bit_cg[1];
        csrng__RECOV_ALERT_STS_fld_cg fld_cg;
        rand dv_base_reg_field ENABLE_FIELD_ALERT;
        rand dv_base_reg_field SW_APP_ENABLE_FIELD_ALERT;
        rand dv_base_reg_field READ_INT_STATE_FIELD_ALERT;
        rand dv_base_reg_field FIPS_FORCE_ENABLE_FIELD_ALERT;
        rand dv_base_reg_field ACMD_FLAG0_FIELD_ALERT;
        rand dv_base_reg_field CS_BUS_CMP_ALERT;
        rand dv_base_reg_field CMD_STAGE_INVALID_ACMD_ALERT;
        rand dv_base_reg_field CMD_STAGE_INVALID_CMD_SEQ_ALERT;
        rand dv_base_reg_field CMD_STAGE_RESEED_CNT_ALERT;

        function new(string name = "csrng__RECOV_ALERT_STS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.ENABLE_FIELD_ALERT = dv_base_reg_field::type_id::create("ENABLE_FIELD_ALERT");
            this.ENABLE_FIELD_ALERT.configure(this, 1, 0, "W0C", 1, 'h0, 0, 1, 1);
            this.SW_APP_ENABLE_FIELD_ALERT = dv_base_reg_field::type_id::create("SW_APP_ENABLE_FIELD_ALERT");
            this.SW_APP_ENABLE_FIELD_ALERT.configure(this, 1, 1, "W0C", 1, 'h0, 0, 1, 1);
            this.READ_INT_STATE_FIELD_ALERT = dv_base_reg_field::type_id::create("READ_INT_STATE_FIELD_ALERT");
            this.READ_INT_STATE_FIELD_ALERT.configure(this, 1, 2, "W0C", 1, 'h0, 0, 1, 1);
            this.FIPS_FORCE_ENABLE_FIELD_ALERT = dv_base_reg_field::type_id::create("FIPS_FORCE_ENABLE_FIELD_ALERT");
            this.FIPS_FORCE_ENABLE_FIELD_ALERT.configure(this, 1, 3, "W0C", 1, 'h0, 0, 1, 1);
            this.ACMD_FLAG0_FIELD_ALERT = dv_base_reg_field::type_id::create("ACMD_FLAG0_FIELD_ALERT");
            this.ACMD_FLAG0_FIELD_ALERT.configure(this, 1, 4, "W0C", 1, 'h0, 0, 1, 1);
            this.CS_BUS_CMP_ALERT = dv_base_reg_field::type_id::create("CS_BUS_CMP_ALERT");
            this.CS_BUS_CMP_ALERT.configure(this, 1, 12, "W0C", 1, 'h0, 0, 1, 1);
            this.CMD_STAGE_INVALID_ACMD_ALERT = dv_base_reg_field::type_id::create("CMD_STAGE_INVALID_ACMD_ALERT");
            this.CMD_STAGE_INVALID_ACMD_ALERT.configure(this, 1, 13, "W0C", 1, 'h0, 0, 1, 1);
            this.CMD_STAGE_INVALID_CMD_SEQ_ALERT = dv_base_reg_field::type_id::create("CMD_STAGE_INVALID_CMD_SEQ_ALERT");
            this.CMD_STAGE_INVALID_CMD_SEQ_ALERT.configure(this, 1, 14, "W0C", 1, 'h0, 0, 1, 1);
            this.CMD_STAGE_RESEED_CNT_ALERT = dv_base_reg_field::type_id::create("CMD_STAGE_RESEED_CNT_ALERT");
            this.CMD_STAGE_RESEED_CNT_ALERT.configure(this, 1, 15, "W0C", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(ENABLE_FIELD_ALERT_bit_cg[bt]) ENABLE_FIELD_ALERT_bit_cg[bt] = new();
                foreach(SW_APP_ENABLE_FIELD_ALERT_bit_cg[bt]) SW_APP_ENABLE_FIELD_ALERT_bit_cg[bt] = new();
                foreach(READ_INT_STATE_FIELD_ALERT_bit_cg[bt]) READ_INT_STATE_FIELD_ALERT_bit_cg[bt] = new();
                foreach(FIPS_FORCE_ENABLE_FIELD_ALERT_bit_cg[bt]) FIPS_FORCE_ENABLE_FIELD_ALERT_bit_cg[bt] = new();
                foreach(ACMD_FLAG0_FIELD_ALERT_bit_cg[bt]) ACMD_FLAG0_FIELD_ALERT_bit_cg[bt] = new();
                foreach(CS_BUS_CMP_ALERT_bit_cg[bt]) CS_BUS_CMP_ALERT_bit_cg[bt] = new();
                foreach(CMD_STAGE_INVALID_ACMD_ALERT_bit_cg[bt]) CMD_STAGE_INVALID_ACMD_ALERT_bit_cg[bt] = new();
                foreach(CMD_STAGE_INVALID_CMD_SEQ_ALERT_bit_cg[bt]) CMD_STAGE_INVALID_CMD_SEQ_ALERT_bit_cg[bt] = new();
                foreach(CMD_STAGE_RESEED_CNT_ALERT_bit_cg[bt]) CMD_STAGE_RESEED_CNT_ALERT_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__RECOV_ALERT_STS

    // reg - csrng::ERR_CODE
    class csrng__ERR_CODE extends dv_base_reg;
        `uvm_object_utils(csrng__ERR_CODE)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__ERR_CODE_bit_cg SFIFO_CMD_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_GENBITS_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_CMDREQ_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_RCSTAGE_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_KEYVRC_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_UPDREQ_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_BENCREQ_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_BENCACK_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_PDATA_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_FINAL_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_GBENCACK_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_GRCSTAGE_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_GGENREQ_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_GADSTAGE_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_GGENBITS_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg SFIFO_BLKENC_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg CMD_STAGE_SM_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg MAIN_SM_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg DRBG_GEN_SM_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg DRBG_UPDBE_SM_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg DRBG_UPDOB_SM_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg AES_CIPHER_SM_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg CMD_GEN_CNT_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg FIFO_WRITE_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg FIFO_READ_ERR_bit_cg[1];
        csrng__ERR_CODE_bit_cg FIFO_STATE_ERR_bit_cg[1];
        csrng__ERR_CODE_fld_cg fld_cg;
        rand dv_base_reg_field SFIFO_CMD_ERR;
        rand dv_base_reg_field SFIFO_GENBITS_ERR;
        rand dv_base_reg_field SFIFO_CMDREQ_ERR;
        rand dv_base_reg_field SFIFO_RCSTAGE_ERR;
        rand dv_base_reg_field SFIFO_KEYVRC_ERR;
        rand dv_base_reg_field SFIFO_UPDREQ_ERR;
        rand dv_base_reg_field SFIFO_BENCREQ_ERR;
        rand dv_base_reg_field SFIFO_BENCACK_ERR;
        rand dv_base_reg_field SFIFO_PDATA_ERR;
        rand dv_base_reg_field SFIFO_FINAL_ERR;
        rand dv_base_reg_field SFIFO_GBENCACK_ERR;
        rand dv_base_reg_field SFIFO_GRCSTAGE_ERR;
        rand dv_base_reg_field SFIFO_GGENREQ_ERR;
        rand dv_base_reg_field SFIFO_GADSTAGE_ERR;
        rand dv_base_reg_field SFIFO_GGENBITS_ERR;
        rand dv_base_reg_field SFIFO_BLKENC_ERR;
        rand dv_base_reg_field CMD_STAGE_SM_ERR;
        rand dv_base_reg_field MAIN_SM_ERR;
        rand dv_base_reg_field DRBG_GEN_SM_ERR;
        rand dv_base_reg_field DRBG_UPDBE_SM_ERR;
        rand dv_base_reg_field DRBG_UPDOB_SM_ERR;
        rand dv_base_reg_field AES_CIPHER_SM_ERR;
        rand dv_base_reg_field CMD_GEN_CNT_ERR;
        rand dv_base_reg_field FIFO_WRITE_ERR;
        rand dv_base_reg_field FIFO_READ_ERR;
        rand dv_base_reg_field FIFO_STATE_ERR;

        function new(string name = "csrng__ERR_CODE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.SFIFO_CMD_ERR = dv_base_reg_field::type_id::create("SFIFO_CMD_ERR");
            this.SFIFO_CMD_ERR.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_GENBITS_ERR = dv_base_reg_field::type_id::create("SFIFO_GENBITS_ERR");
            this.SFIFO_GENBITS_ERR.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_CMDREQ_ERR = dv_base_reg_field::type_id::create("SFIFO_CMDREQ_ERR");
            this.SFIFO_CMDREQ_ERR.configure(this, 1, 2, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_RCSTAGE_ERR = dv_base_reg_field::type_id::create("SFIFO_RCSTAGE_ERR");
            this.SFIFO_RCSTAGE_ERR.configure(this, 1, 3, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_KEYVRC_ERR = dv_base_reg_field::type_id::create("SFIFO_KEYVRC_ERR");
            this.SFIFO_KEYVRC_ERR.configure(this, 1, 4, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_UPDREQ_ERR = dv_base_reg_field::type_id::create("SFIFO_UPDREQ_ERR");
            this.SFIFO_UPDREQ_ERR.configure(this, 1, 5, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_BENCREQ_ERR = dv_base_reg_field::type_id::create("SFIFO_BENCREQ_ERR");
            this.SFIFO_BENCREQ_ERR.configure(this, 1, 6, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_BENCACK_ERR = dv_base_reg_field::type_id::create("SFIFO_BENCACK_ERR");
            this.SFIFO_BENCACK_ERR.configure(this, 1, 7, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_PDATA_ERR = dv_base_reg_field::type_id::create("SFIFO_PDATA_ERR");
            this.SFIFO_PDATA_ERR.configure(this, 1, 8, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_FINAL_ERR = dv_base_reg_field::type_id::create("SFIFO_FINAL_ERR");
            this.SFIFO_FINAL_ERR.configure(this, 1, 9, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_GBENCACK_ERR = dv_base_reg_field::type_id::create("SFIFO_GBENCACK_ERR");
            this.SFIFO_GBENCACK_ERR.configure(this, 1, 10, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_GRCSTAGE_ERR = dv_base_reg_field::type_id::create("SFIFO_GRCSTAGE_ERR");
            this.SFIFO_GRCSTAGE_ERR.configure(this, 1, 11, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_GGENREQ_ERR = dv_base_reg_field::type_id::create("SFIFO_GGENREQ_ERR");
            this.SFIFO_GGENREQ_ERR.configure(this, 1, 12, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_GADSTAGE_ERR = dv_base_reg_field::type_id::create("SFIFO_GADSTAGE_ERR");
            this.SFIFO_GADSTAGE_ERR.configure(this, 1, 13, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_GGENBITS_ERR = dv_base_reg_field::type_id::create("SFIFO_GGENBITS_ERR");
            this.SFIFO_GGENBITS_ERR.configure(this, 1, 14, "RO", 1, 'h0, 0, 1, 1);
            this.SFIFO_BLKENC_ERR = dv_base_reg_field::type_id::create("SFIFO_BLKENC_ERR");
            this.SFIFO_BLKENC_ERR.configure(this, 1, 15, "RO", 1, 'h0, 0, 1, 1);
            this.CMD_STAGE_SM_ERR = dv_base_reg_field::type_id::create("CMD_STAGE_SM_ERR");
            this.CMD_STAGE_SM_ERR.configure(this, 1, 20, "RO", 1, 'h0, 0, 1, 1);
            this.MAIN_SM_ERR = dv_base_reg_field::type_id::create("MAIN_SM_ERR");
            this.MAIN_SM_ERR.configure(this, 1, 21, "RO", 1, 'h0, 0, 1, 1);
            this.DRBG_GEN_SM_ERR = dv_base_reg_field::type_id::create("DRBG_GEN_SM_ERR");
            this.DRBG_GEN_SM_ERR.configure(this, 1, 22, "RO", 1, 'h0, 0, 1, 1);
            this.DRBG_UPDBE_SM_ERR = dv_base_reg_field::type_id::create("DRBG_UPDBE_SM_ERR");
            this.DRBG_UPDBE_SM_ERR.configure(this, 1, 23, "RO", 1, 'h0, 0, 1, 1);
            this.DRBG_UPDOB_SM_ERR = dv_base_reg_field::type_id::create("DRBG_UPDOB_SM_ERR");
            this.DRBG_UPDOB_SM_ERR.configure(this, 1, 24, "RO", 1, 'h0, 0, 1, 1);
            this.AES_CIPHER_SM_ERR = dv_base_reg_field::type_id::create("AES_CIPHER_SM_ERR");
            this.AES_CIPHER_SM_ERR.configure(this, 1, 25, "RO", 1, 'h0, 0, 1, 1);
            this.CMD_GEN_CNT_ERR = dv_base_reg_field::type_id::create("CMD_GEN_CNT_ERR");
            this.CMD_GEN_CNT_ERR.configure(this, 1, 26, "RO", 1, 'h0, 0, 1, 1);
            this.FIFO_WRITE_ERR = dv_base_reg_field::type_id::create("FIFO_WRITE_ERR");
            this.FIFO_WRITE_ERR.configure(this, 1, 28, "RO", 1, 'h0, 0, 1, 1);
            this.FIFO_READ_ERR = dv_base_reg_field::type_id::create("FIFO_READ_ERR");
            this.FIFO_READ_ERR.configure(this, 1, 29, "RO", 1, 'h0, 0, 1, 1);
            this.FIFO_STATE_ERR = dv_base_reg_field::type_id::create("FIFO_STATE_ERR");
            this.FIFO_STATE_ERR.configure(this, 1, 30, "RO", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(SFIFO_CMD_ERR_bit_cg[bt]) SFIFO_CMD_ERR_bit_cg[bt] = new();
                foreach(SFIFO_GENBITS_ERR_bit_cg[bt]) SFIFO_GENBITS_ERR_bit_cg[bt] = new();
                foreach(SFIFO_CMDREQ_ERR_bit_cg[bt]) SFIFO_CMDREQ_ERR_bit_cg[bt] = new();
                foreach(SFIFO_RCSTAGE_ERR_bit_cg[bt]) SFIFO_RCSTAGE_ERR_bit_cg[bt] = new();
                foreach(SFIFO_KEYVRC_ERR_bit_cg[bt]) SFIFO_KEYVRC_ERR_bit_cg[bt] = new();
                foreach(SFIFO_UPDREQ_ERR_bit_cg[bt]) SFIFO_UPDREQ_ERR_bit_cg[bt] = new();
                foreach(SFIFO_BENCREQ_ERR_bit_cg[bt]) SFIFO_BENCREQ_ERR_bit_cg[bt] = new();
                foreach(SFIFO_BENCACK_ERR_bit_cg[bt]) SFIFO_BENCACK_ERR_bit_cg[bt] = new();
                foreach(SFIFO_PDATA_ERR_bit_cg[bt]) SFIFO_PDATA_ERR_bit_cg[bt] = new();
                foreach(SFIFO_FINAL_ERR_bit_cg[bt]) SFIFO_FINAL_ERR_bit_cg[bt] = new();
                foreach(SFIFO_GBENCACK_ERR_bit_cg[bt]) SFIFO_GBENCACK_ERR_bit_cg[bt] = new();
                foreach(SFIFO_GRCSTAGE_ERR_bit_cg[bt]) SFIFO_GRCSTAGE_ERR_bit_cg[bt] = new();
                foreach(SFIFO_GGENREQ_ERR_bit_cg[bt]) SFIFO_GGENREQ_ERR_bit_cg[bt] = new();
                foreach(SFIFO_GADSTAGE_ERR_bit_cg[bt]) SFIFO_GADSTAGE_ERR_bit_cg[bt] = new();
                foreach(SFIFO_GGENBITS_ERR_bit_cg[bt]) SFIFO_GGENBITS_ERR_bit_cg[bt] = new();
                foreach(SFIFO_BLKENC_ERR_bit_cg[bt]) SFIFO_BLKENC_ERR_bit_cg[bt] = new();
                foreach(CMD_STAGE_SM_ERR_bit_cg[bt]) CMD_STAGE_SM_ERR_bit_cg[bt] = new();
                foreach(MAIN_SM_ERR_bit_cg[bt]) MAIN_SM_ERR_bit_cg[bt] = new();
                foreach(DRBG_GEN_SM_ERR_bit_cg[bt]) DRBG_GEN_SM_ERR_bit_cg[bt] = new();
                foreach(DRBG_UPDBE_SM_ERR_bit_cg[bt]) DRBG_UPDBE_SM_ERR_bit_cg[bt] = new();
                foreach(DRBG_UPDOB_SM_ERR_bit_cg[bt]) DRBG_UPDOB_SM_ERR_bit_cg[bt] = new();
                foreach(AES_CIPHER_SM_ERR_bit_cg[bt]) AES_CIPHER_SM_ERR_bit_cg[bt] = new();
                foreach(CMD_GEN_CNT_ERR_bit_cg[bt]) CMD_GEN_CNT_ERR_bit_cg[bt] = new();
                foreach(FIFO_WRITE_ERR_bit_cg[bt]) FIFO_WRITE_ERR_bit_cg[bt] = new();
                foreach(FIFO_READ_ERR_bit_cg[bt]) FIFO_READ_ERR_bit_cg[bt] = new();
                foreach(FIFO_STATE_ERR_bit_cg[bt]) FIFO_STATE_ERR_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__ERR_CODE

    // reg - csrng::ERR_CODE_TEST
    class csrng__ERR_CODE_TEST extends dv_base_reg;
        `uvm_object_utils(csrng__ERR_CODE_TEST)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__ERR_CODE_TEST_bit_cg ERR_CODE_TEST_bit_cg[5];
        csrng__ERR_CODE_TEST_fld_cg fld_cg;
        rand dv_base_reg_field ERR_CODE_TEST;

        function new(string name = "csrng__ERR_CODE_TEST");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.ERR_CODE_TEST = dv_base_reg_field::type_id::create("ERR_CODE_TEST");
            this.ERR_CODE_TEST.configure(this, 5, 0, "RW", 1, 'h0, 0, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(ERR_CODE_TEST_bit_cg[bt]) ERR_CODE_TEST_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__ERR_CODE_TEST

    // reg - csrng::MAIN_SM_STATE
    class csrng__MAIN_SM_STATE extends dv_base_reg;
        `uvm_object_utils(csrng__MAIN_SM_STATE)
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        csrng__MAIN_SM_STATE_bit_cg MAIN_SM_STATE_bit_cg[8];
        csrng__MAIN_SM_STATE_fld_cg fld_cg;
        rand dv_base_reg_field MAIN_SM_STATE;

        function new(string name = "csrng__MAIN_SM_STATE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.MAIN_SM_STATE = dv_base_reg_field::type_id::create("MAIN_SM_STATE");
            this.MAIN_SM_STATE.configure(this, 8, 0, "RO", 1, 'h4e, 1, 1, 1);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(MAIN_SM_STATE_bit_cg[bt]) MAIN_SM_STATE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : csrng__MAIN_SM_STATE

    // addrmap - csrng
    class csrng extends dv_base_reg_block;
        `uvm_object_utils(csrng)
        rand csrng__INTERRUPT_STATE INTERRUPT_STATE;
        rand csrng__INTERRUPT_ENABLE INTERRUPT_ENABLE;
        rand csrng__INTERRUPT_TEST INTERRUPT_TEST;
        rand csrng__ALERT_TEST ALERT_TEST;
        rand csrng__REGWEN REGWEN;
        rand csrng__CTRL CTRL;
        rand csrng__CMD_REQ CMD_REQ;
        rand csrng__RESEED_INTERVAL RESEED_INTERVAL;
        rand csrng__RESEED_COUNTER RESEED_COUNTER[3];
        rand csrng__SW_CMD_STS SW_CMD_STS;
        rand csrng__GENBITS_VLD GENBITS_VLD;
        rand csrng__GENBITS GENBITS;
        rand csrng__INT_STATE_READ_ENABLE INT_STATE_READ_ENABLE;
        rand csrng__INT_STATE_READ_ENABLE_REGWEN INT_STATE_READ_ENABLE_REGWEN;
        rand csrng__INT_STATE_NUM INT_STATE_NUM;
        rand csrng__INT_STATE_VAL INT_STATE_VAL;
        rand csrng__FIPS_FORCE FIPS_FORCE;
        rand csrng__HW_EXC_STS HW_EXC_STS;
        rand csrng__RECOV_ALERT_STS RECOV_ALERT_STS;
        rand csrng__ERR_CODE ERR_CODE;
        rand csrng__ERR_CODE_TEST ERR_CODE_TEST;
        rand csrng__MAIN_SM_STATE MAIN_SM_STATE;

        function new(string name = "csrng");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.INTERRUPT_STATE = csrng__INTERRUPT_STATE::type_id::create("INTERRUPT_STATE");
            this.INTERRUPT_STATE.configure(this);

            this.INTERRUPT_STATE.build();
            this.default_map.add_reg(this.INTERRUPT_STATE, 'h0);
            this.INTERRUPT_ENABLE = csrng__INTERRUPT_ENABLE::type_id::create("INTERRUPT_ENABLE");
            this.INTERRUPT_ENABLE.configure(this);

            this.INTERRUPT_ENABLE.build();
            this.default_map.add_reg(this.INTERRUPT_ENABLE, 'h4);
            this.INTERRUPT_TEST = csrng__INTERRUPT_TEST::type_id::create("INTERRUPT_TEST");
            this.INTERRUPT_TEST.configure(this);

            this.INTERRUPT_TEST.build();
            this.default_map.add_reg(this.INTERRUPT_TEST, 'h8);
            this.ALERT_TEST = csrng__ALERT_TEST::type_id::create("ALERT_TEST");
            this.ALERT_TEST.configure(this);

            this.ALERT_TEST.build();
            this.default_map.add_reg(this.ALERT_TEST, 'hc);
            this.REGWEN = csrng__REGWEN::type_id::create("REGWEN");
            this.REGWEN.configure(this);

            this.REGWEN.build();
            this.default_map.add_reg(this.REGWEN, 'h10);
            this.CTRL = csrng__CTRL::type_id::create("CTRL");
            this.CTRL.configure(this);

            this.CTRL.build();
            this.default_map.add_reg(this.CTRL, 'h14);
            this.CMD_REQ = csrng__CMD_REQ::type_id::create("CMD_REQ");
            this.CMD_REQ.configure(this);

            this.CMD_REQ.build();
            this.default_map.add_reg(this.CMD_REQ, 'h18);
            this.RESEED_INTERVAL = csrng__RESEED_INTERVAL::type_id::create("RESEED_INTERVAL");
            this.RESEED_INTERVAL.configure(this);

            this.RESEED_INTERVAL.build();
            this.default_map.add_reg(this.RESEED_INTERVAL, 'h1c);
            foreach(this.RESEED_COUNTER[i0]) begin
                this.RESEED_COUNTER[i0] = csrng__RESEED_COUNTER::type_id::create($sformatf("RESEED_COUNTER[%0d]", i0));
                this.RESEED_COUNTER[i0].configure(this);

                this.RESEED_COUNTER[i0].build();
                this.default_map.add_reg(this.RESEED_COUNTER[i0], 'h20 + i0*'h4);
            end
            this.SW_CMD_STS = csrng__SW_CMD_STS::type_id::create("SW_CMD_STS");
            this.SW_CMD_STS.configure(this);

            this.SW_CMD_STS.build();
            this.default_map.add_reg(this.SW_CMD_STS, 'h2c);
            this.GENBITS_VLD = csrng__GENBITS_VLD::type_id::create("GENBITS_VLD");
            this.GENBITS_VLD.configure(this);

            this.GENBITS_VLD.build();
            this.default_map.add_reg(this.GENBITS_VLD, 'h30);
            this.GENBITS = csrng__GENBITS::type_id::create("GENBITS");
            this.GENBITS.configure(this);

            this.GENBITS.build();
            this.default_map.add_reg(this.GENBITS, 'h34);
            this.INT_STATE_READ_ENABLE = csrng__INT_STATE_READ_ENABLE::type_id::create("INT_STATE_READ_ENABLE");
            this.INT_STATE_READ_ENABLE.configure(this);

            this.INT_STATE_READ_ENABLE.build();
            this.default_map.add_reg(this.INT_STATE_READ_ENABLE, 'h38);
            this.INT_STATE_READ_ENABLE_REGWEN = csrng__INT_STATE_READ_ENABLE_REGWEN::type_id::create("INT_STATE_READ_ENABLE_REGWEN");
            this.INT_STATE_READ_ENABLE_REGWEN.configure(this);

            this.INT_STATE_READ_ENABLE_REGWEN.build();
            this.default_map.add_reg(this.INT_STATE_READ_ENABLE_REGWEN, 'h3c);
            this.INT_STATE_NUM = csrng__INT_STATE_NUM::type_id::create("INT_STATE_NUM");
            this.INT_STATE_NUM.configure(this);

            this.INT_STATE_NUM.build();
            this.default_map.add_reg(this.INT_STATE_NUM, 'h40);
            this.INT_STATE_VAL = csrng__INT_STATE_VAL::type_id::create("INT_STATE_VAL");
            this.INT_STATE_VAL.configure(this);

            this.INT_STATE_VAL.build();
            this.default_map.add_reg(this.INT_STATE_VAL, 'h44);
            this.FIPS_FORCE = csrng__FIPS_FORCE::type_id::create("FIPS_FORCE");
            this.FIPS_FORCE.configure(this);

            this.FIPS_FORCE.build();
            this.default_map.add_reg(this.FIPS_FORCE, 'h48);
            this.HW_EXC_STS = csrng__HW_EXC_STS::type_id::create("HW_EXC_STS");
            this.HW_EXC_STS.configure(this);

            this.HW_EXC_STS.build();
            this.default_map.add_reg(this.HW_EXC_STS, 'h4c);
            this.RECOV_ALERT_STS = csrng__RECOV_ALERT_STS::type_id::create("RECOV_ALERT_STS");
            this.RECOV_ALERT_STS.configure(this);

            this.RECOV_ALERT_STS.build();
            this.default_map.add_reg(this.RECOV_ALERT_STS, 'h50);
            this.ERR_CODE = csrng__ERR_CODE::type_id::create("ERR_CODE");
            this.ERR_CODE.configure(this);

            this.ERR_CODE.build();
            this.default_map.add_reg(this.ERR_CODE, 'h54);
            this.ERR_CODE_TEST = csrng__ERR_CODE_TEST::type_id::create("ERR_CODE_TEST");
            this.ERR_CODE_TEST.configure(this);

            this.ERR_CODE_TEST.build();
            this.default_map.add_reg(this.ERR_CODE_TEST, 'h58);
            this.MAIN_SM_STATE = csrng__MAIN_SM_STATE::type_id::create("MAIN_SM_STATE");
            this.MAIN_SM_STATE.configure(this);

            this.MAIN_SM_STATE.build();
            this.default_map.add_reg(this.MAIN_SM_STATE, 'h5c);
        endfunction : build
    endclass : csrng

    typedef class csrng_reg_block;

    `include "csrng_sample.svh"
    `include "csrng_reg_block.sv"
endpackage: csrng_uvm
